server:
  port: 8765
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h[%I] %l %u %t %r %s %b %D[ms]"
    basedir: .

endpoints:
  enabled: true


codis:
  enables: cache_training

logging:
  config: classpath:log4j2-${APP_ENV:dev}.xml

spring.data.mongodb.uri:
  mongodb://localhost:27017/nexthotel